services:
  init-webapp-logs:
    image: alpine:3.19
    command: ["sh", "-c", "mkdir -p /tmp/webapp-logs && chown -R 65532:65532 /tmp/webapp-logs"]
    volumes:
      - webapp-logs:/tmp/webapp-logs
    restart: "no"

  webapp:
    container_name: webapp
    build:
      context: .
    environment:
      - PORT=8080
    volumes:
      - webapp-logs:/tmp/webapp-logs
    ports:
      - "8080:8080"
    depends_on:
      - loki
      - init-webapp-logs

  loki:
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/config.yml
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yml:/etc/loki/config.yml:ro
      - loki-data:/loki

  promtail:
    image: grafana/promtail:2.9.3
    command: -config.file=/etc/promtail/config.yml
    depends_on:
      - loki
      - init-webapp-logs
    volumes:
      - ./promtail-config.yml:/etc/promtail/config.yml:ro
      - webapp-logs:/tmp/webapp-logs:ro

  grafana:
    image: grafana/grafana:10.4.2
    ports:
      - "9090:3000"
    depends_on:
      - loki
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning:ro

volumes:
  loki-data:
  grafana-data:
  webapp-logs:
